"use client";

import Link from "next/link";
import { motion } from "framer-motion";

export default function PrivacyPolicy() {
  return (
    <div className="flex flex-col min-h-screen bg-black text-white w-full">
      <main className="flex-1 w-full max-w-4xl mx-auto pt-[120px] pb-24 px-4 md:px-8">
        
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <h1 className="text-4xl md:text-6xl font-bold tracking-tighter mb-12 text-white">
            Privacy Policy
          </h1>

          <div className="space-y-12 text-white/70 leading-relaxed text-lg">
            
            {/* Data Controller */}
            <section>
              <h2 className="text-white text-xl font-medium uppercase tracking-widest mb-4">
                1. Data Controller
              </h2>
              <p>
                The Data Controller is <strong>Gabriel Mihali</strong>. 
                For any inquiries regarding your personal data, you can reach me at: 
                <span className="text-white ml-1">contact@gabrielmihali.com</span>.
              </p>
            </section>

            {/* Statistics and Cookies */}
            <section>
              <h2 className="text-white text-xl font-medium uppercase tracking-widest mb-4">
                2. Statistics and Cookies
              </h2>
              <p>
                This website is designed with a privacy-first approach. It does not use profiling or tracking cookies. 
                I exclusively use <strong>Cloudflare Web Analytics</strong>, an analytics service that collects data in a 
                completely anonymous and aggregated form without the use of cookies, in full compliance with privacy 
                regulations (including Art. 122 of the Italian Privacy Code and GDPR).
              </p>
            </section>

            {/* Contact Form */}
            <section>
              <h2 className="text-white text-xl font-medium uppercase tracking-widest mb-4">
                3. Contact Form
              </h2>
              <p>
                By filling out the contact form, you voluntarily provide your Name, Email, and Company name. 
                This data is used <strong>exclusively</strong> to respond to your inquiries. 
                The legal basis for this processing is the execution of pre-contractual measures or your explicit consent.
              </p>
            </section>

            {/* Third Parties */}
            <section>
              <h2 className="text-white text-xl font-medium uppercase tracking-widest mb-4">
                4. Data Transfer and Third Parties
              </h2>
              <p>
                For the technical management and delivery of emails generated by the contact form, this site uses 
                <strong> Resend</strong>, appointed as an External Data Processor. Resend ensures high security standards; 
                data passes through their servers only for the time strictly necessary to forward the message to my mailbox.
              </p>
            </section>

            {/* User Rights */}
            <section>
              <h2 className="text-white text-xl font-medium uppercase tracking-widest mb-4">
                5. Your Rights
              </h2>
              <p>
                You have the right to access your data, request its rectification, erasure, or restriction of processing at any time. 
                To exercise these rights, simply send an email to the address provided above.
              </p>
            </section>

            <div className="pt-12 border-t border-white/10">
              <Link href="/about" className="text-white hover:text-white/60 transition-colors flex items-center gap-2">
                ← Back to Contacts
              </Link>
            </div>
          </div>
        </motion.div>
      </main>
    </div>
  );
}